### ISSUE TITLE
[Q] How to install Taiga in Portainer?

### ISSUE THREAD

**Issue by luk6173** [taigaio/taiga-docker#101]
Hi,

how I can install Taiga in Portainer? Has anyone already installed Taiga in Portainer? A how-to would be cool!

Thank you,
Lukas

**Comment by Bodo-von-Greif** [comment]
Hi Lukas,

Dockerfiles handling are called Stacks in Portainer.

There you can create a stack and copy/paste Dockerfile content.

If you use docker-compose you will see the containers in Portainer too,

I managed to run kaleidos ventures taiga docker but i think the Dockerfile construct is not suitable for portainer stacks.

best 

Bodo

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
