### ISSUE TITLE
[BUG] many vulnerabilities in docker images

### ISSUE THREAD

**Issue by JLammering** [taigaio/taiga-docker#102]
**Describe the bug**
The docker images have many vulnerabilities including some high and critical ones. Could you update the images?

**How can we reproduce the behavior**
docker scan taigaio/taiga-back

**Screenshots**
![grafik](https://user-images.githubusercontent.com/15649818/201625038-714b6191-6b60-48ad-8867-361d948e105a.png)

**Comment by yamila-moreno** [comment]
Hi there @JLammering, thank you very much for noticing this.
We've updated the image, so you can pull `taigaio/taiga-back:latest` and use it with the slim image up to date.

**Comment by JLammering** [comment]
Hi, thanks for updating that image. Its solved for that one. Unfortunately its the same with all other images in your [docker-compose.yml](https://github.com/kaleidos-ventures/taiga-docker/blob/main/docker-compose.yml ). There are often critical and high severity vulnerabilities.

**Comment by yamila-moreno** [comment]
hi @JLammering we have just pushed the other 3 images with the base images up to date:
- taigaio/taiga-front:latest
- taigaio/taiga-events:latest
- taigaio/taiga-protected:latest
