### ISSUE TITLE
[BUG] : Taiga installation with docker shows error screen, penpot working

### ISSUE THREAD

**Issue by Akshaychdev** [taigaio/taiga-docker#119]
### Issue

Tried taiga installation as per the [documentation](https://community.taiga.io/t/taiga-30min-setup/170#github-oauth-login-17).
But after containers spawned up and superuser created, getting this error startup screen.
No containers failed status/ none showing any visible ERRORs  at `docker log <container>`.

![image](https://github.com/kaleidos-ventures/taiga-docker/assets/63786863/98c004ac-3be5-4c45-9921-b4ee866d8613)

Used the default `.env` settings (as it is for testing), used the `./launch-all.sh` script, penpot seems working fine.

![image](https://github.com/kaleidos-ventures/taiga-docker/assets/63786863/9a671900-b8b8-44f4-9cc6-13fab7314dc5)

### Environment.

Docker version: 24.0.6
Os version: Ubuntu 22.04.3 LTS
Project branch: Stable

Spawned containers

![image](https://github.com/kaleidos-ventures/taiga-docker/assets/63786863/cd7052fc-a664-43a6-94e7-09d1eda33898)

### Logs

DB container - taiga-docker-taiga-db-1

```
2023-10-20 10:24:52.281 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-10-20 10:24:52.337 UTC [86] LOG:  database system was shut down at 2023-10-20 10:24:52 UTC
2023-10-20 10:24:52.352 UTC [1] LOG:  database system is ready to accept connections
```

There are no errors showing in other container logs

`./taiga-manage.sh migrate` shows no migrations.

### What I've tried so far

* Removed the containers and volumes `docker compose down && docker container prune && docker volume prune -a` and relaunched multiple times with default `.env` configuration with both `launch-all.sh` and `launch-taiga.sh` but with no sucess.

Mention if anything missing using default http -> with public Ip for testing.

**Comment by stamenminkov** [comment]
@Akshaychdev did you manage to solve that?

**Comment by linwaysdevops** [comment]
> @Akshaychdev did you manage to solve that?

Yes it was due to the `.env` settings, the web socket will try to connect to `ws:localhost:9000` - by default,
from your browser it is not accessible - you can just see the error in browser js console,
it is the default value given in the `.env` file, change that to your real web url,

Default

```bash
TAIGA_SCHEME=http  # serve Taiga using "http" or "https" (secured) connection
TAIGA_DOMAIN=localhost:9000  # Taiga's base URL
SUBPATH=""  # it'll be appended to the TAIGA_DOMAIN (use either "" or a "/subpath")
WEBSOCKETS_SCHEME=ws  # events connection protocol (use either "ws" or "wss")
```

Change this if you are using `http://<YOUR PUB IP>:9000` to test taiga
Remember to allow the inbound connections to port `9000` in your network/firewall settings.

```bash
TAIGA_SCHEME=http
TAIGA_DOMAIN=<YOUR IP>
SUBPATH=""
WEBSOCKETS_SCHEME=ws
```

If you are using your subdomain with nginx reverse proxy

```bash
TAIGA_SCHEME=https
TAIGA_DOMAIN=taiga.mycompany.com
SUBPATH=""
WEBSOCKETS_SCHEME=wss
```

docker container will expose the port `9000`.

**Comment by Akshaychdev** [comment]
> @Akshaychdev did you manage to solve that?

Yes it was due to the `.env` settings, the web socket will try to connect to `ws:localhost:9000` - by default,
from your browser it is not accessible - you can just see the error in browser js console,
it is the default value given in the `.env` file, change that to your real web url,

Default

```bash
TAIGA_SCHEME=http  # serve Taiga using "http" or "https" (secured) connection
TAIGA_DOMAIN=localhost:9000  # Taiga's base URL
SUBPATH=""  # it'll be appended to the TAIGA_DOMAIN (use either "" or a "/subpath")
WEBSOCKETS_SCHEME=ws  # events connection protocol (use either "ws" or "wss")
```

Change this if you are using `http://<YOUR PUB IP>:9000` to test taiga
Remember to allow the inbound connections to port `9000` in your network/firewall settings.

```bash
TAIGA_SCHEME=http
TAIGA_DOMAIN=<YOUR IP>
SUBPATH=""
WEBSOCKETS_SCHEME=ws
```

If you are using your subdomain with nginx reverse proxy

```bash
TAIGA_SCHEME=https
TAIGA_DOMAIN=taiga.mycompany.com
SUBPATH=""
WEBSOCKETS_SCHEME=wss
```

docker container will expose the port `9000`.
