### ISSUE TITLE
[Q] Media URL and Server URL in Emails is None

### ISSUE THREAD

**Issue by lpilz** [taigaio/taiga-docker#12]
Hi there,
after setting up the Docker, Taiga is now running. However, apparently, the media URL is None. If I e.g. try to change my profile picture, it is not shown and inspecting the page yields the URL `https://none/media/user/a/7/e/a/7e3d550e5d01f081ddb9a0868bbf58ff5ec9dcb650326502810cfc3972af/profile_pic.png.80x80_q85_crop.jpg?token=<token>`. I tried setting the old MEDIA_URL variable in `taiga-front`, but this didn't work.

Please find by docker-compose files attached.

Thanks in advance!
[docker-compose.txt](https://github.com/kaleidos-ventures/taiga-docker/files/6539101/docker-compose.txt)
[docker-compose-inits.txt](https://github.com/kaleidos-ventures/taiga-docker/files/6539102/docker-compose-inits.txt)

**Comment by lpilz** [comment]
This also affects the server URL in Emails (e.g. for resetting password or verifying email)

**Comment by tdelatorre** [comment]
Hi @lpilz

In your docker-compose in x-environment you have:
TAIGA_URL: taiga.myserver.org
but this should be:
TAIGA_SITES_DOMAIN: taiga.myserver.org

Then you can delete:
MEDIA_URL: "https://taiga.myserver.org/media"
STATIC_URL: "https://taiga.myserver.org/static"
in taiga-front service.

More info [here](https://docs.taiga.io/setup-production.html#_configuration).

I hope this helps!
Regards

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
