### ISSUE TITLE
Internal Server Error 500 and and websocket connection error[Q] 

### ISSUE THREAD

**Issue by dekm** [taigaio/taiga-docker#13]
I've installed taiga on my server and not able to get past the discovery screen to log in. Checking dev tools I can see these errors appear in the communication layer.

500 (Internal Server Error)
WebSocket connection to 'wss://xx.xx.xx.xx:9000/events' failed: 
![taiga_errors](https://user-images.githubusercontent.com/9221328/119621528-e7a37180-be0e-11eb-8470-407e89fd0425.png)

I have opened port 9000 in shorewall although not certain if other ports are required.

**Comment by bameda** [comment]
@dekm please, review your logs (and share with us), specially taiga-back logs. The main problems is not related to websocket connection (taiga can runs without websocket). The problems is why the API (taiga-back) returns 500.

**Comment by dekm** [comment]
> @dekm please, review your logs (and share with us), specially taiga-back logs. The main problems is not related to websocket connection (taiga can runs without websocket). The problems is why the API (taiga-back) returns 500.

It appears that resolv.conf was missing read permisions for anyone other than root. So we've had to enter a few containers to give them read permissions. Both backend and taiga-events container. Events container exits as soon as it fails.

**Comment by dekm** [comment]
chmod o+r /var/lib/docker/containers/*/resolv.conf

Forces them all to have the correct permissions in docker.
