### ISSUE TITLE
[FR] Document backup & restore

### ISSUE THREAD

**Issue by yamila-moreno** [taigaio/taiga-docker#14]
In taiga-doc we should add the recommended way to backup & restore Taiga

**Comment by yamila-moreno** [comment]
@nuokh ping! Let me know if this is ok for you! I'm happy to help you and answer any questions you may have :D 

To implement this:

`Backup and Restore` should go in the first level, which means:
- a new file called `backup-and-restore.adoc`
- a new section in `index.adoc` called "Backup and Restore Guide"
- a couple of lines in `Makefile`

**The "backup"** part should:
- pg_dump the database from the container, something like:
```
$ docker exec database-container pg_dump -U taiga taiga > taiga.sql
```
- tar the **media** files inside the container, `docker cp` them outside and remove the tar

Anyone should only need to backup the database and the media files but exclude the static files, cause they are recollected anytime with Django `collectstatic`.

**The "restore"** part should follow essentially the instructions given in the documentation to migrate from source-code to docker. These instructions are [here](https://docs.taiga.io/upgrades-5to6.html#_load_the_old_dump).

**Comment by nuokh** [comment]
Thanks for pointing me in the right direction. I'll try to tackle it this weekend!

**Comment by nuokh** [comment]
Done! https://github.com/kaleidos-ventures/taiga-doc/pull/5

**Comment by yamila-moreno** [comment]
As https://github.com/kaleidos-ventures/taiga-doc/pull/5 is already merged, we can close this issue.
