### ISSUE TITLE
[Q] Admin credentials wrong ?

### ISSUE THREAD

**Issue by DaFray31** [taigaio/taiga-docker#16]
Hello,

I installed taigo following the tutorial, everything works except the admin account. I go to the `/admin/` page, 
I enter `admin `and `123123`
But it doesn't work, I don't see any errors (`just : "Please fill in the "username" and "password" fields of an authorised account correctly. Please note that both fields may be case sensitive."`)

For information, I use portainer & Nginx proxy manager

**Comment by gerroon** [comment]
I have the same issue

**Comment by DaFray31** [comment]
I just forgot to do : `$ ./taiga-manage.sh createsuperuser`

**Comment by gerroon** [comment]
In my case, I already created the admin user, still had issues.
