### ISSUE TITLE
Broken Events URL

### ISSUE THREAD

**Issue by GryphonWorx** [taigaio/taiga-docker#18]
In the docker-compose.yml file I initially put in wss://mydomain for the TAIGA_WEBSOCKETS_URL, but this causes a ERR_DISALLOWED_URL_SCHEME on Chrome and Edge Chromimum. I remember having a similar issue when I ran Taiga 5 from source and changed it to run over https instead. But this doesn't work with this image since it makes the URL wss://mydomain.net/https://mydomain.net/events on its own, causing connection errors.

Is there some preferred method of configuring this so it does work? I can't have my users configure their browsers to allow unsafe settings so hopefully there's some method of telling Taiga to stop tacking on the wss path? I've double checked my settings and the path provided there isn't present anywhere. It's just set to https://mydomain.

This is for the Stable release.

**Comment by yamila-moreno** [comment]
just to check, the TAIGA_WEBSOCKETS_URL should be a complete URL, like `wss://mydomain.com`; did you configure that?

You can see the final configuration regarding websockets with:

`docker exec taiga-docker_taiga-front_1 head /usr/share/nginx/html/conf.json`

**Comment by GryphonWorx** [comment]
Yes, if I set the TAIGA_WEBSOCKETS_URL to wss://mydomain.com and refresh the docker the browser console spits out a bunch of 502 errors trying to connect to wss://mydomain.com (the ERR_DISALLOWED_URL_SCHEME error). If I change the TAIGA_WEBSOCKETS_URL to https://mydomain.com the browser console spits out error connecting to wss://mydomain.com/https://mydomain.com/events

Using the command you posted above shows that the eventsUrl is indeed set to https://mydomain.com/events so I am not sure where the wss address is coming from since I've not written that anywhere. Is it somehow deriving this?

**Comment by yamila-moreno** [comment]
hi @GryphonWorx I think it was an error documenting the proxy configuration. Could you try with this configuration?

```
server {
    listen 443 ssl;
    server_name taiga.mydomain.com;
    ...

    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Scheme $scheme;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_pass http://localhost:9000/;
    }

    # Events
    location /events {
        proxy_pass http://localhost:9000/events;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }

}
```

**Comment by GryphonWorx** [comment]
That didn't solve the issue either, sadly. Neither with https or wss protocol in the TAIGA_WEBSOCKETS_URL settings. My proxy settings are now exactly as shown in your post there.

However, there may be more configuration issues since I now get requests to localhost:9000 when trying to i.e. change my profile picture. Is there something else I need to proxy for this?

i.e.
GET localhost:9000/media/user/b/6/e/8/9d035a8ea801df611106b82c5e160bf3f16e69287b512b8a17c0f24cc84a/download.png.80x80_q85_crop.png?token=YBlb8w%3A8hBTg33MIIVT2x5nYXxBaOxUm7JX08KrryvDuraKPorSDO9tzDjakMVn9xgQrzO34_LV_dSXVuX5fEjCN_NIig

**Comment by yamila-moreno** [comment]
can you confirm that your taiga-front service has both these env vars configured?

```
  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "https://mydomain.com"
      TAIGA_WEBSOCKETS_URL: "wss://mydomain.com"
```
if it's making API requests to localhost is seems that the TAIGA_URL is pointing to localhost (this is the base_url for the API in the front service).

**Comment by GryphonWorx** [comment]
That is exactly what it's saying, or, well https://taiga.mydomain.com and wss://taiga.mydomain.com.

**Comment by yamila-moreno** [comment]
and with the command I sent you before, can you confirm what's the "api" value?
`docker exec taiga-docker_taiga-front_1 head /usr/share/nginx/html/conf.json`

**Comment by GryphonWorx** [comment]
The issue with the images was my fault, I had misunderstood the purpose of  TAIGA_SITES_DOMAIN in the x-environment. I changed that to the live domain and images etc now work. We're back to just having the websocket error now.

**Running that command if I have TAIGA_WEBSOCKETS_URL set to wss://taiga.mydomain.com:**
"eventsUrl": "wss://taiga.mydomain.com/events. The error I get is still ERR_DISALLOWED_URL_SCHEME in the browser.

**If I have TAIGA_WEBSOCKETS_URL set to https://taiga.mydomain.com:**
"eventsUrl": "https://taiga.mydomain.com/events" but the socket tries to connect to "wss://taiga.mydomain.com/https://taiga.mydomain.com/events" again.

**Comment by yamila-moreno** [comment]
ok! one problem solved, let's go to the original with websockets.

### Configuration
You have (or should have):

**docker-compose.yml**
```
  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "https://taiga.mydomain.com"
      TAIGA_WEBSOCKETS_URL: "wss://taiga.mydomain.com"
```

**proxy**
If you're using nginx, you should have something like this in your own proxy configuration (mind the /events location)
```
server {
    listen 443 ssl;
    server_name taiga.mydomain.com;

    # your TLS configured, your logs, and so on

    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Scheme $scheme;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_pass http://localhost:9000/;
    }

    # Events
    location /events {
        proxy_pass http://localhost:9000/events;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }

}
```
### Debugging

That said:
- could you send the logs of your proxy?
- the logs of taiga-gateway?
- the logs of taiga-events?

**Comment by GryphonWorx** [comment]
I think I might have solved it. First restoring the configuration as you said and then editing the nginx http->https forwarding rule. It was checking $scheme != "https" which would then break wss connections. After refreshing the instances and restarting nginx it seems to work. My bad :P

**Comment by yamila-moreno** [comment]
cool! glad you figured it out!!! I'm closing then the issue :+1:

**Comment by mohammadrafigh** [comment]
For anyone who comes here, I solved this problem by adding these configurations both for `/events` proxy and taiga-gateway `/events`:

```
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
