### ISSUE TITLE
[Q] Attachments gives me 404

### ISSUE THREAD

**Issue by gerroon** [taigaio/taiga-docker#18]
Hi

I am using this Docker setup. As far as I can tell everything works except opening the attachments in the Issues or Kanban issues.

I am able to attach them to the issues alright without error. I also see them written to the media volume I provided. So theya re definetely uploaded, it seems to be an issue with showing them in the frontend when clicked on them.

My url is `http:\\taiga.lan:9090` I had to change the port since it was taken already. I added `taiga.lan` to my hosts

I am accessing it from the local network so no proxy is involved. Looking at the error, it seems like the media serving is not considering the port.

I get

```
http://taiga.lan/media/attachments/0/2/2/a/24f30eb70431157a3cdd7f32d839ed2fa4de50f3f42bbbc75936ba599a17/szegedzsinagoga.jpg?token=YL109w%3AIopecqMaCfzOz6g_F44Yo8FKIfn3pyUEzbK_Isiagcw3HPvwCNcUtsDbD7cLI2LGjxBuvxegBJlAt1xS-NFQEA 404 (Not Found)
Image (async)
a @ app.js:3022

Show 197 more frames
/media/attachments/0/2/2/a/24f30eb70431157a3cdd7f32d839ed2fa4de50f3f42bbbc75936ba599a17/szegedzsinagoga.jpg?token=YL11Bg%3AZT-gW0b8xyOXbDaTuCMyAdbiOiK-ThAi2TaqvWFC4oL-hA_ZhlfoZNizHi-6olBmwX1-V7mb4jUux0awebMiPA#_taiga-refresh=userstory:4:1 GET http://taiga.lan/media/attachments/0/2/2/a/24f30eb70431157a3cdd7f32d839ed2fa4de50f3f42bbbc75936ba599a17/szegedzsinagoga.jpg?token=YL11Bg%3AZT-gW0b8xyOXbDaTuCMyAdbiOiK-ThAi2TaqvWFC4oL-hA_ZhlfoZNizHi-6olBmwX1-V7mb4jUux0awebMiPA 4

```

**Comment by bameda** [comment]
IIt could be a misconfiguration issue. It seems that the final url does not contain the port. Have you tried url adding the port?  Could you share the content of your docker-compose file?

**Comment by gerroon** [comment]
@bameda 
You were right. I was using the "taiga.lan" for the TAIGA_SITES_DOMAIN. Including the port solves the issue it seems. Thanks for the help.

**Comment by bameda** [comment]
Yeah!! You are welcome.
