### ISSUE TITLE
[Q] the correct way to fix invalid conf.json file.

### ISSUE THREAD

**Issue by diggymo** [taigaio/taiga-docker#20]
Please tell me the correct way to fix invalid conf.json file.

#### background

After I cloned from git, this commands runs.

```
$ ./launch-taiga.sh
$ ./taiga-manage.sh createsuperuser
```

Because I wanted to view taiga, I visited to `http://localhost:5900`. But it was displayed on the screen.

>Something happened and the Taiga has captured the error to be able to work on it.

And in chrome dev tool console `Your conf.json file is not a valid json file, please review it.`

So I checked the conf.json by accesing `http://localhost:5900/conf.json`. 

My conf.json is below.

```
{
    "api": "http://localhost:9000/api/v1/",
    "eventsUrl": "ws://localhost:9000/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": false,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "defaultLoginEnabled": true,
    "publicRegisterEnabled": ,
    "feedbackEnabled": true,
    "supportUrl": "https://resources.taiga.io",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [
      "/plugins/slack/slack.json",
      "/plugins/github-auth/github-auth.json",
      "/plugins/gitlab-auth/gitlab-auth.json"
    ],
    "gitHubClientId": "",
    "gitLabClientId": "",
    "gitLabUrl": "",
    "tagManager": { "accountId": null },
    "tribeHost": null,
    "enableAsanaImporter": false,
    "enableGithubImporter": ,
    "enableJiraImporter": ,
    "enableTrelloImporter": ,
    "gravatar": false,
    "rtlLanguages": ["fa"]
}

```

There were four parts where the structure is broken.

1. `"publicRegisterEnabled": ,`
2. "enableGithubImporter": ,
3. "enableJiraImporter": ,
4. "enableTrelloImporter": ,

So, I modified conf.json on the fly (by editing /usr/share/nginx/html/conf.json), but how should I modify it?

**Comment by bameda** [comment]
This should be a problem in your `docker-compose.yml` file. Because this settings are case sensitive for front and back.

![image](https://user-images.githubusercontent.com/877218/121347965-126de980-c928-11eb-82e1-b06eda18cfdb.png)

So use `True` and `False` for the back settings and `true` and `false` for the front settings.

You can find more info at https://resources.taiga.io/30min-setup/

**Comment by bameda** [comment]
The CORS error should be fixed when your conf.json will be fine.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
