### ISSUE TITLE
Cant access django admin page

### ISSUE THREAD

**Issue by masihmoloodian** [taigaio/taiga-docker#20]
I trying to access admin page with route /admin, base on nginx config
but i cant access it

container taiga-docker_taiga-back_1 logs:

Executing pending migrations
Operations to perform:
  Apply all migrations: admin, attachments, auth, bitbucket, contact, contenttypes, custom_attributes, djmail, easy_thumbnails, epics, external_apps, feedback, github, gitlab, gogs, history, issues, likes, milestones, notifications, projects, references, sessions, settings, taiga_contrib_slack, tasks, telemetry, timeline, users, userstorage, userstories, votes, webhooks, wiki
Running migrations:
  No migrations to apply.
Load default templates
Installed 2 object(s) from 1 fixture(s)
Give permission to taiga:taiga
Starting Taiga API...
[2021-02-02 12:08:19 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2021-02-02 12:08:19 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2021-02-02 12:08:19 +0000] [1] [INFO] Using worker: sync
[2021-02-02 12:08:19 +0000] [30] [INFO] Booting worker with pid: 30
[2021-02-02 12:08:19 +0000] [31] [INFO] Booting worker with pid: 31
[2021-02-02 12:08:19 +0000] [32] [INFO] Booting worker with pid: 32

**Comment by tdelatorre** [comment]
To access into backoffice on localhost with http connections you need to add SESSION_COOKIE_SECURE and CSRF_COOKIE_SECURE to x-environment in docker-compose.yml and change their value to "False". 
More info [here](https://resources.taiga.io/30min-setup/) and more info about this environment variables [here](https://docs.djangoproject.com/en/3.1/ref/settings/#csrf-cookie-secure)

**Comment by masihmoloodian** [comment]
I added to , x-environment in docker-compose.yml but still i cant access admin page.
at nginx-alpine container, it cant access to taiga backend on port 8000

**Comment by tdelatorre** [comment]
What's the result if you do `docker ps | grep taiga`?

Your host configuration needs to make a proxy to http://localhost:9000. 
Example:

```
server {
  server_name taiga.mycompany.com;
  ...
  location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_pass http://localhost:9000/;
  }
}
```

Could you access to http://localhost:9000/api/v1/ ? (don't forget the forward slash at the end) What's the result?

What's the result when you go to http://localhost:9000/admin/ ? (don't forget the forward slash at the end)

**Comment by masihmoloodian** [comment]
Output of docker ps | grep taiga

```
8f750be0e2dd   redis:6       "docker-entrypoint.s…"   4 days ago   Up 2 days   6379/tcp   taiga-docker_penpot-redis_1
5220a54857f0   postgres:13   "docker-entrypoint.s…"   4 days ago   Up 2 days   5432/tcp   taiga-docker_penpot-postgres_1
```

**Comment by masihmoloodian** [comment]
thanks, that's work

**Comment by swiss-knight** [comment]
More precision to @tdelatorre first post according to the django documentation: https://docs.djangoproject.com/en/3.1/ref/settings/ 

> SESSION_COOKIE_SECURE
>
> Default: False
>
>Whether to use a secure cookie for the session cookie. If this is set to True, the cookie will be marked as “secure”, which means browsers may ensure that the cookie is only sent under an HTTPS connection.
>
>Leaving this setting off isn’t a good idea because an attacker could capture an unencrypted session cookie with a packet sniffer and use the cookie to hijack the user’s session.

And

>CSRF_COOKIE_SECURE
>
>Default: False
>
>Whether to use a secure cookie for the CSRF cookie. If this is set to True, the cookie will be marked as “secure”, which means browsers may ensure that the cookie is only sent with an HTTPS connection.

I guess they should be set to `True` when HTTPS is used.
