### ISSUE TITLE
Give permission to taiga:taiga takes too much time

### ISSUE THREAD

**Issue by mohammadrafigh** [taigaio/taiga-docker#21]
**Describe the bug**
Running taiga-back with a lot of media files takes more than 10 mins at `Give permission to taiga:taiga` stage!

**Expected behavior**
I don't think there is a need to run `chown taiga:taiga` in entrypoint.sh

**Comment by yamila-moreno** [comment]
hi @mohammadrafigh thanks for reporting.

You're right this should not take so long. We're addressing it from different approaches; we'll update this issue as soon as we have a new solution.

**Comment by yamila-moreno** [comment]
hi @mohammadrafigh could you tell us the size of this media directory?

**Comment by mohammadrafigh** [comment]
It's around 800MB but with a lot of images and documents.

**Comment by yamila-moreno** [comment]
I've just tested with more than 90k files (in different directories) inside a container and the time is barely noticeable:

```sh
root@07b2c8d33061:/miles# time chown -R root:root /miles/
real	0m0.316s
user	0m0.076s
sys	0m0.238s
```

I've also found that there is a [known problem](https://github.com/docker/for-linux/issues/388) with performance in file system of volumes related to certain versions of docker and kernel.

Would you consider trying with a different version of kernel/docker?

**Comment by mohammadrafigh** [comment]
Thanks for the info. VPS uses kernel v3.* but docker is at the latest
version. Maybe the kernel is the issue. We can close this issue. Thanks for
being responsible.

**Comment by swiss-knight** [comment]
I also encounter a 5min lag between 
```
taiga-back_1             | Give permission to taiga:taiga
```
and 
```
taiga-back_1             | Starting Taiga API...
```
Kernel of the host machine is: 5.4.0-65-generic x86_64 GNU/Linux
