### ISSUE TITLE
Many domain ?

### ISSUE THREAD

**Issue by oldgnoah1379** [taigaio/taiga-docker#22]
please show me there a way to use multiple domains for taiga?

**Comment by bameda** [comment]
Hi @gnoah1379 can you explain what you want to do with multiples domains and what is the use case (why do you need)???

Are you using the docker-compose or the bare-metal  process??

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
