### ISSUE TITLE
Include LDAP contrib plugin

### ISSUE THREAD

**Issue by laopisai** [taigaio/taiga-docker#24]
**Is your feature request related to a problem? Please describe.**
We are using ldap contrib plugin in our self-hosted instance and is planning to migrate to Taiga 6 in Docker. However, we think that it is not straightforward to install the plugin (taiga-contrib-ldap-auth-ext) without Taiga 6's Dockerfile.

**Describe the solution you'd like**
Either taiga-contrib-ldap-auth-ext to be included by default or the Dockerfile is published for us to install in ourselves

**Describe alternatives you've considered**
Upgrade to Taiga 6 source-code version

**Comment by laopisai** [comment]
Just realised that the Dockerfile is supplied in taiga-back repo. Anyway keeping this open in case there's interest to add it by default

**Comment by yamila-moreno** [comment]
Hi @laopisai; currently we only distribute plugins that are maintained by the core dev team. We'll be improving the way you can install plugins in the docker distribution, but probably it won't get as soon as you need.

Meanwhile, you can build your own docker images. Have in mind that:
- you need to change `docker/config.py` to have/read the new variables
- you need to compile the taiga-front image as well
- in doubt, build over the latest tag in stable brach

good luck!!
