### ISSUE TITLE
docs issue

### ISSUE THREAD

**Issue by burtsevyg** [taigaio/taiga-docker#25]
At https://github.com/taigaio/taiga-docker#taiga-back
link https://github.com/taigaio/taiga-back/blob/taiga-6/docker/config.py
does not work

**Comment by burtsevyg** [comment]
The right link:
curl -O https://raw.githubusercontent.com/taigaio/taiga-back/master/docker/config.py

**Comment by yamila-moreno** [comment]
fixed! thanks for reporting!
