### ISSUE TITLE
doc issue 2

### ISSUE THREAD

**Issue by burtsevyg** [taigaio/taiga-docker#26]
At the page: https://taigaio.github.io/taiga-doc/dist/upgrades-5to6.html#taiga5-to-taiga6dckr

1.4 ...Advanced configuration: if you have a local.py with some complex settings, you can ignore the environment variables and map a config.py file (check the x-volumes section in docker-compose.yml)...

Where I can find config.py in my installation? Only find local.py
Can I map local.py as config.py?

**Comment by yamila-moreno** [comment]
In taiga5 the configuration file was typically `local.py` (it was used by default) and from taiga6 is `config.py` (the name is just a convention and you can name it whatever you want). We recommend that you use the [`config.py.prod.example`](https://github.com/taigaio/taiga-back/blob/master/settings/config.py.prod.example) and overwrite with your `local.py` specific data.
You can map in a volume a file called `local.py` into a containter:config.py but a taiga5 `local.py` file probably will not work properly in taiga6.
