### ISSUE TITLE
Doc: inconsistency in the docker documentation

### ISSUE THREAD

**Issue by swiss-knight** [taigaio/taiga-docker#28]
At: https://taigaio.github.io/taiga-doc/dist/setup-production.html#setup-prod-with-docker 
one can read:

> From taiga-front download the file dist/config.example.json and rename it:
```
mv dist/config.example.json dist/config.json
```
(+ is that a typo? shouldn't this be `conf.json` instead of `config.json`?)

The `dist/` folder is usually not committed, hence one cannot find it at: https://github.com/taigaio/taiga-front

There are two conf.json file there;    
- conf/conf.example.json
- docker/conf.json.template

So, in the docker install documentation, one should point to one of these two instead.

**Comment by yamila-moreno** [comment]
Hi @swiss-knight you're right this is an error in the documentation; the fix is already deployed. Thanks for reporting!
