### ISSUE TITLE
Webhooks not working properly

### ISSUE THREAD

**Issue by psclrzn** [taigaio/taiga-docker#29]
**Describe the bug**
It appears that when you run Taiga from Docker, the Webhooks are not working properly.  When I test the webhook with the webhook, it works, but when I make changes to a task, or anything else, it doesn't seem to send the changes to the webhooks.

I added WEBHOOKS_ENABLED = True in my local.py but it doesn't seem to change anything.

**To Reproduce**
1. Configure Taiga in Docker like mentioned in the Get Started section.
2. Create a project with a Webhook.
3. Press the test button for the Webhook (Test Payload should be sent)
4. Add a user story, edit a user story, or any action that should trigger the Webhook.

**Expected behavior**
The payload should be sent with every actions made.

**Configuration**
No custom configuration.  Except for the WEBHOOKS_ENABLED mentioned above.

**Versions**
 - docker 3.1.0 (51484)
 - docker-compose 1.27.4 build 40524192

**Additional context**
Windows 10 Pro 2004

**Comment by yamila-moreno** [comment]
Hi @psclrzn if you're using docker and docker-compose with no customisation, you don't need a local.py. Nonetheless, are you mapping this file? if you have a `local.py`I guess you're updating from taiga5. This requires updating the local.py (we recommend to copy the config.py and putting there your configuration from local.py).

But probably you don't need this. Could you provide more information about how did you configure your instance?

**Comment by psclrzn** [comment]
Honestly, I haven't done much in terms of configuration.  I started everything from scratch.  I had no other Taiga instance running, and didn't upgrade any instance.

I downloaded the zip file from the repo and ran the launch-all.sh script from Powershell.  Then I opened the CLI for docker-back from Docker Desktop and ran the manage script to create a super user.

The local.py part was because of this issue : https://github.com/taigaio/taiga-back/issues/878.  I know it's not for Taiga 6, but tried it anyway.

**Comment by yamila-moreno** [comment]
Ok, so let's forget about `local.py` as it's not used.

You're using the taigaio/taiga-docker repository from scratch. I believe you followed the  [30min-setup](https://resources.taiga.io/30min-setup/), is that correct?

The first step is to check that everything works out of the box; for that:
- clone the `taiga-docker` repository
- ensure you have the newest taiga images (pull them again, we've released some fixed)
- run `./launch-taiga.sh` in your terminal and wait (**use the docker-compose.yml variables as they are, don't change**). do you have any errors so far?
- after that, in the same terminal, you should run `./taiga-mange.sh createsuperuser` and create a new superuser
- go to `http://localhost:9000` and you should have a taiga instance

Can you confirm that, with these steps, you have a Taiga working locally?

**Comment by psclrzn** [comment]
I get an error message about the` ./taiga-manage.sh createsuperuser`.  

> Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.

So I went into the taiga-back CLI from docker and ran `python manage.py createsuperuser` and created my default user.

If I go to `http://localhost:9000` and log in, it works.

I created a new private project, define a webhook to `webhook.site` and tested it: it works.

I create a user story in the project, moved the user story around, and I see no event sent to the webhook.

I switched the project to public, and it doesn't change anything: I still can't see the events sent to the webhook.

BTW: This is from another Windows 10 machine, running the latest docker and docker-compose versions.

**Comment by yamila-moreno** [comment]
> I get an error message about the` ./taiga-manage.sh createsuperuser`.
> 
> > Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.
> 
> So I went into the taiga-back CLI from docker and ran `python manage.py createsuperuser` and created my default user.

with `taiga-back CLI from docker` you mean you jumped into the container (with `docker exec -ti...`) and then you run this command?
That would be correct.

> 
> If I go to `http://localhost:9000` and log in, it works.

cool!

> I created a new private project, define a webhook to `webhook.site` and tested it: it works.

How do you do this? Which webhook are you configuring? and where?

> I create a user story in the project, moved the user story around, and I see no event sent to the webhook.

This is automatically managed by taiga-events, but you don't need to configure anything special for these events. I'm a bit confused here because "real time" is managed with taiga-events with websockets, and webhooks serve to integrate with Github issues for instance.

> 
> I switched the project to public, and it doesn't change anything: I still can't see the events sent to the webhook.
> 
> BTW: This is from another Windows 10 machine, running the latest docker and docker-compose versions.

**Comment by psclrzn** [comment]
Under `Settings > Integrations > Webhooks`, you can add Webhooks.

![image](https://user-images.githubusercontent.com/41126535/107246365-2f3bf400-69fe-11eb-89c2-9a2313c7d134.png)

But if I use that same webhook the same ways in a hosted instance of Taiga (on tree.taiga.io), it works.

**Comment by yamila-moreno** [comment]
ok! this is definetly a bug! Thanks for reporting!

We've just published a patch-release that fixed it. You can pull again taigaio/taiga-back:latest and try again. Let us know if it's working properly.

**Comment by psclrzn** [comment]
It works now!  Great!  Thank you.

Another thing that I found, though, is that there is a slight display error in the Webhook page.

![image](https://user-images.githubusercontent.com/41126535/107268074-acbf2e80-6a15-11eb-83fc-4df4af8dfe23.png)

When you create a webhook and test it with the Test button, the initial state of the history button is "Hide History" instead of "Show History".

Do you want me to open an other issue for that?  Or will you take care of it in this ticket?

**Comment by yamila-moreno** [comment]
Ey cool it worked!!
I noticed the same thing and opened the issue already: https://tree.taiga.io/project/taiga/issue/4258
