### ISSUE TITLE
[Q] Apache proxy

### ISSUE THREAD

**Issue by gusarg81** [taigaio/taiga-docker#30]
Hi,

I want to know the full settings needed for Apache reverse proxy. So far I can't make it work:

Taiga (does not work, error page):

> ProxyPreserveHost On
> 
> ProxyPass http://localhost:9000/
> ProxyPassReverse http://localhost:9000/
> 
> RewriteEngine On
> RewriteCond %{HTTP:Upgrade} =websocket [NC]
> RewriteRule ^/events/(.*)    ws://localhost:9000/events/$1 [P,L]

Penpot (blank page):

> ProxyPass http://localhost:9001/
> ProxyPassReverse http://localhost:9001/

Nothing was changed in docker files, just default as it is.

Thanks in advance.

**Comment by gusarg81** [comment]
Hi,

I made this work by trying to put all together all information I can get and I never realized that in docker settings/env, all URL should be the domain url and not the localhost of the docker. So, in Apache Proxy:

> ProxyPass "/" "http://localhost:9000/" connectiontimeout=5 timeout=30 keepalive=on
> ProxyPassReverse "/" "http://localhost:9000/"
> 
> RewriteEngine on
> RewriteCond %{HTTP:Upgrade} websocket [NC]
> RewriteCond %{HTTP:Connection} upgrade [NC]
> RewriteRule ^/?(.*) "ws://localhost:9000//$1" [P,L]
> 
> ProxyPass "/events" "ws://localhost:9000/events" connectiontimeout=5 timeout=30 keepalive=on
> ProxyPassReverse "/events" "ws://localhost:9000/events"

Then, in my case my domain is "projects.gdnet.ar" and strictly via SSL. So, in docker-compose.yml:

> TAIGA_SITES_DOMAIN: "projects.gdnet.ar"
> TAIGA_SITES_SCHEME: "https"
>
> TAIGA_URL: "https://projects.gdnet.ar"
> TAIGA_WEBSOCKETS_URL: "wss://projects.gdnet.ar"

After all this, it does work with Apache and Proxy.

I think the docs should be more explicit about this, most of all, what values should be in docker files/settings.

**Comment by gusarg81** [comment]
By the way, I still receiving web socket connection error on the browser, even Taiga website is working.

Does anyone has the right Proxy configuration for Apache please?...

**Comment by gerroon** [comment]
While I do not have an answer for the socket error, I am looking for a proxy config for subfolder as in DOMAIN/taiga.

**Comment by gusarg81** [comment]
> While I do not have an answer for the socket error, I am looking for a proxy config for subfolder as in DOMAIN/taiga.

Have you tested adding the subfolder?

**Comment by gerroon** [comment]
I could not make it work, I think semething about websocket was not working.

**Comment by TheBlapse** [comment]
> Hi,
> 
> I made this work by trying to put all together all information I can get and I never realized that in docker settings/env, all URL should be the domain url and not the localhost of the docker. So, in Apache Proxy:
> 
> > ProxyPass "/" "http://localhost:9000/" connectiontimeout=5 timeout=30 keepalive=on
> > ProxyPassReverse "/" "http://localhost:9000/"
> > RewriteEngine on
> > RewriteCond %{HTTP:Upgrade} websocket [NC]
> > RewriteCond %{HTTP:Connection} upgrade [NC]
> > RewriteRule ^/?(.*) "ws://localhost:9000//$1" [P,L]
> > ProxyPass "/events" "ws://localhost:9000/events" connectiontimeout=5 timeout=30 keepalive=on
> > ProxyPassReverse "/events" "ws://localhost:9000/events"
> 
> Then, in my case my domain is "projects.gdnet.ar" and strictly via SSL. So, in docker-compose.yml:
> 
> > TAIGA_SITES_DOMAIN: "projects.gdnet.ar"
> > TAIGA_SITES_SCHEME: "https"
> > TAIGA_URL: "https://projects.gdnet.ar"
> > TAIGA_WEBSOCKETS_URL: "wss://projects.gdnet.ar"
> 
> After all this, it does work with Apache and Proxy.
> 
> I think the docs should be more explicit about this, most of all, what values should be in docker files/settings.

@gusarg81 
Do you have Public Registration enabled? if so is it working? I have used the same proxy config as yours but It's not working with my case and giving wss error

![image](https://user-images.githubusercontent.com/76247922/142719810-d1659e9b-e862-4eb4-8fd3-8cb668b4cb26.png)

**Comment by gusarg81** [comment]
I don´t have public registration enabled.

BTW, still have websocket errors but seems the platform is working nice.

Only thing, the docker cointainers related to Taiga do crash randomly and I have to start them all again.

**Comment by TheBlapse** [comment]
> I don´t have public registration enabled.
> 
> BTW, still have websocket errors but seems the platform is working nice.
> 
> Only thing, the docker cointainers related to Taiga do crash randomly and I have to start them all again.

Oh

**Comment by TheBlapse** [comment]
> I don´t have public registration enabled.
> 
> BTW, still have websocket errors but seems the platform is working nice.
> 
> Only thing, the docker cointainers related to Taiga do crash randomly and I have to start them all again.

@gusarg81 If its disabled then how do you use it like how does other members log in etc? or you use it personally only?

**Comment by gusarg81** [comment]
Because is not public, is only for my Team. So, I create the additional users if needed.

**Comment by TheBlapse** [comment]
> Because is not public, is only for my Team. So, I create the additional users if needed.

@gusarg81 Btw I managed it to working and now don't have websockets error as well, what I did is: 

```shell
docker stop taiga-docker_taiga-gateway_1
```
and then again
```shell
docker-compose up -d
```

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
