### ISSUE TITLE
Volumes error

### ISSUE THREAD

**Issue by pablomenino** [taigaio/taiga-docker#32]
**Describe the bug**

Some links like admin/ and static/ doesn't work properly. I think is an error on my gateway configuration (nginx), need help.

Taiga works fine. I can access to admin/, but I can't access to static/, so doesn't load properly. Same problem api/v1/

![alt text](https://i.imgur.com/TQ23237.png)

**To Reproduce**
1. apply custom config
2. docker-compose up -d
3. taiga is behind of NGINX Proxy, traffic for taiga.example.com is redirected to taiga IP port 9011 (HTTPS Port)

**Expected behavior**
See admin page, and have access to api/v1/ Gateway configuration error for admin/ and static/?

**Configuration**

I send the link to files:

[docker-compose-inits.yml](https://drive.google.com/file/d/1szK-789-k0w1IsBhQBI78UI1AJWXMZ2g/view?usp=sharing)

[docker-compose.yml](https://drive.google.com/file/d/1Y1RHf7CmdsvKFbrQMlRqOGkSLuplAQlz/view?usp=sharing)

[taiga.conf](https://drive.google.com/file/d/1TziqdYfOIoNF8fgKtretFoe5Lo6ipj76/view?usp=sharing)

**Versions**
 - Docker version 18.09.8, build bfed4f5
 - docker-compose version 1.24.0, build 0aa59064

**Comment by pablomenino** [comment]
I see my error, I cannot share a volume in 2 containers when the volume was mounted in a directory.

In database I can mount a directory on the server without problems to make the DB persistent, but /media and /static are being shared on the front and the back containers,.

There is another way to mount /static and /media to a local folder in the server?

**Comment by yamila-moreno** [comment]
Hi @pablomenino I'm not sure I'm understanding the problem here. Back and front don't share volumes. Back and gateway do.

The taiga.conf file is the file in your nginx? the file you linked is in the taiga-gateway service, and in your nginx should be way more simple, as you can see in the [30min-setup](https://resources.taiga.io/30min-setup/).

were you updating from taiga5 to taiga6? why cannot you use a named volume as suggested?

**Comment by pablomenino** [comment]
I resolve some issues, right known if I mount this volume in back:

- /volume1/docker/taigaio/static:/taiga-back/static

And this volume in gateway:

- /volume1/docker/taigaio/static:/taiga/static

I have the issue of the screenshot, Some links like admin/ and static/ doesn't work properly.

If I mount this way works fine:

back:
 - taiga-static-data:/taiga-back/static

gateway:
 - taiga-static-data:/taiga/static

Is not a fault on nginx configuration (gateway).

The taiga.conf is the the nginx configuration in taiga-gateway service.

This is the only issue I have, and is with the static folder.

**Comment by yamila-moreno** [comment]
@pablomenino the problem is only in the `/admin` app or in taiga as well?

Are you accessing via http://localhost:9000/admin/ or via domain https://taiga.mycompany.com?
Have you changed the configuration? are you using a custom configuration or the default configuration?

**Comment by pablomenino** [comment]
The problem is only in the /admin/, but is because the /static/ files., like you can see in the screenshot on first post.

I am accessing via domain https://taiga.example.com/admin/

No change in configuration.

**Comment by uhlhosting** [comment]
@pablomenino have you managed to solve the issue? I kinda face the same issue when trying to add ssl into current taiga-gateway config.

**Comment by yamila-moreno** [comment]
hi @uhlhosting the taiga.conf in taiga-gateway is configured assuming that TSL is solved in the host. The intention is that you configure your TSL in your host nginx/caddy/apache and it redirects to the 9000 port.

If you want to add the certificates to taiga-gateway, you'll need to map a new taiga.conf besides the certificates. 

Cheers!

**Comment by pablomenino** [comment]
Thanks @yamila-moreno @bameda for the help.

The last configuration that I tested is working without problems, I attach the link to the docker-compose and gateway configuration for future reference.

In the last configuration I am mounting the media and DB volumes in directories to have data persistence.

[Docker-Compose](https://drive.google.com/file/d/1ki6mDkyPZNV2s2h1IWnOK8nx2YRZekP3/view?usp=sharing)

[Gateway SSL configuration](https://drive.google.com/file/d/1ur_pQjaqXtslPsUtqrGVZ-f7uH8iMrtX/view?usp=sharing)

**Comment by yamila-moreno** [comment]
Glad it finally worked!!

Just to prevent other people get confused, with named volumes (or "volumes" in official docker documentation) you can achieve persistance. The way taiga-docker is distributed currently ensures persistance.

More detail can be found [here](https://docs.docker.com/storage/volumes/)

**Comment by uhlhosting** [comment]
> Thanks @yamila-moreno @bameda for the help.
> 
> The last configuration that I tested is working without problems, I attach the link to the docker-compose and gateway configuration for future reference.
> 
> In the last configuration I am mounting the media and DB volumes in directories to have data persistence.
> 
> [Docker-Compose](https://drive.google.com/file/d/1ki6mDkyPZNV2s2h1IWnOK8nx2YRZekP3/view?usp=sharing)
> 
> [Gateway SSL configuration](https://drive.google.com/file/d/1ur_pQjaqXtslPsUtqrGVZ-f7uH8iMrtX/view?usp=sharing)

Will surely give it a try, did you used at any point given 2 taiga.conf configs, like @yamila-moreno described in https://github.com/taigaio/taiga-docker/issues/32#issuecomment-781110700 ?
