### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by nurulakbartan** [taigaio/taiga-docker#32]
Bug i install on my local success

If i install on cloud error 
Something happened and the Taiga has captured the error to be able to work on it.

My local data is still taken to the cloud installation, even though I installed it fresh.

How can solved it?

**Comment by burtsevyg** [comment]
Hello, @nurulakbartan.
Could you please add more details to understand your problem?

**Comment by nurulakbartan** [comment]
After installation in VMWare ubuntu 20.04 , i got some trouble on image below

![image](https://user-images.githubusercontent.com/81746327/126729841-f8dc7295-5687-49dd-8754-227839c89cd1.png)

in docker compose yml 

in part 

  TAIGA_SITES_DOMAIN: "localhost:9000"
  TAIGA_SITES_SCHEME: "http"

i changed into 

  TAIGA_SITES_DOMAIN: "pm.tjakrabirawa.id"
  TAIGA_SITES_SCHEME: "https"

      TAIGA_URL: "http://localhost:9000"
      TAIGA_WEBSOCKETS_URL: "ws://localhost:9000"

i changed into

      TAIGA_URL: "https://pm.tjakrabirawa.id"
      TAIGA_WEBSOCKETS_URL: "ws://pm.tjakrabirawa.id"

**Comment by Xaviju** [comment]
Hi there! 

Do you know that we created [Taiga Community](https://community.taiga.io/c/technical/8) for questions like yours? Please, check there; maybe another user has already asked something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.
