### ISSUE TITLE
Taiga  Something happened and the Taiga has captured the error to be able to work on it.

### ISSUE THREAD

**Issue by m4rkell** [taigaio/taiga-docker#33]
Clean install on ubuntu 20.04 
[https://resources.taiga.io/30min-setup/](https://resources.taiga.io/30min-setup/)

Start the application
`$ ./launch-all.sh`

After some instants, when the application is started you can proceed to create the superuser with the following script:
`$ ./taiga-manage.sh createsuperuser`

**I installed everything according to the instructions. I got to launch. Everything started successfully. I open the page and it says:**
Taiga. Something happened and the Taiga has captured the error to be able to work on it.

**Comment by m4rkell** [comment]
+ SuperUser login not work on **penpot** (9001 port)

**Comment by yamila-moreno** [comment]
Hi @m4rkell 
did you change anything in docker-compose.yml file?
Can you open dev-tools and check which is the API url?

**Comment by m4rkell** [comment]
@yamila-moreno 
Guys, I launched! Everything is fine, but there are two problems left that I cannot solve:

1. How to make sure that after disabling docker and enabling again the database is not erased? I started docker, started projects there, turned off docker, turned on again and the database is empty there are no projects.

2. How to make an autorun on ubuntu, so that after the system boots everything is automatically turned on?

**Comment by yamila-moreno** [comment]
@m4rkell 

>     1. How to make sure that after disabling docker and enabling again the database is not erased? I started docker, started projects there, turned off docker, turned on again and the database is empty there are no projects.

This is how volumes work. I recommend you to take a look at the official documentation of volumes in docker and docker-compose: https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
 
>     2. How to make an autorun on ubuntu, so that after the system boots everything is automatically turned on?

You can take for different approaches:
- configure restart policy in your docker-compose
- create a custom system unit
- put Taiga in an orchestrator

good luck!
