### ISSUE TITLE
[Q] USER_EMAIL_ALLOWED_DOMAINS exposed to docker

### ISSUE THREAD

**Issue by rodrigobrochado** [taigaio/taiga-docker#38]
Hi, the [FAQ](https://docs.taiga.io/setup-faqs.html) mentions that USER_EMAIL_ALLOWED_DOMAINS can be used to restrict user register, but it doesn't seem that it can be set on docker environment. 

If it is the case, could we migrate this to a feature request issue? If it works like other configs, would be a nice config to have no docker. Thanks!!

**Comment by Rollbacke** [comment]
Hi,

You can define it on the `taiga-back` container, in the `/taiga-back/settings/config.py`.

It works. **However**, not quite the way it should.
In fact, when you want to invite someone who isn't from an approved domain, you get stuck on the invitation page, without a message appearing.
We just get stuck there...

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team

**Comment by drbeco** [comment]
@yamila-moreno could you link to the specific topic of the answer for this question?

I tried to search community regarding docker and USER_EMAIL_ALLOWED_DOMAINS to no avail.

Thanks
