### ISSUE TITLE
Attachments return 403 Forbidden

### ISSUE THREAD

**Issue by pabgn** [taigaio/taiga-docker#39]
**Describe the bug**
When accessing attachments, server returns **403 Forbidden**, even though the file has the correct permissions and exists.

**To Reproduce**
1. Following the Update Guide from Taiga5 to Taiga6, the /media folder was copied and permissions were set:
`chown -R taiga:taiga *`
2. /media/user & /media/project files are accessible and visible through the web interface 
3. All the attachments return a 403 Forbidden response

**Example of attachment in server**
`-rw-r--r-- 1 taiga taiga  383530 Dec 16 17:22 image.png`

I think it could have to do with **access tokens or cookies**. Could I disable this protection feature to test it?

**Comment by yamila-moreno** [comment]
Hhi @pabgn have you configured the `taiga-protected` service?

**Comment by pabgn** [comment]
@yamila-moreno that was it. Solved!

**Comment by zeigerpuppy** [comment]
I'm having this same issue.  I have `taiga-protected` running and can see requests for the media coming through there:

```
taiga-gateway  | 2021/04/13 06:49:30 [error] 30#30: *767 open() "/taiga/media//attachments/9/2/d/8/49bb53eaf8b5cb56ed84d9ece67f69bd4686531ebadf200dcb75a87c743d/taiga-gitlab-flow.jpg" failed (2: No such file or directory), client: 192.168.122.44, server: , request: "GET /media/attachments/9/2/d/8/49bb53eaf8b5cb56ed84d9ece67f69bd4686531ebadf200dcb75a87c743d/taiga-gitlab-flow.jpg?token=YHU-9Q%3AV2WrDTqA3kElb9Kw9qRxfTWqdb7HfRDpZFpcaW5sjb1WoYFLJAE7DsVUuUrYLEESQoR3Pch5sOID8XuHeWLg5A HTTP/1.0", upstream: "http://172.18.18.148:8003//attachments/9/2/d/8/49bb53eaf8b5cb56ed84d9ece67f69bd4686531ebadf200dcb75a87c743d/taiga-gitlab-flow.jpg?token=YHU-9Q%3AV2WrDTqA3kElb9Kw9qRxfTWqdb7HfRDpZFpcaW5sjb1WoYFLJAE7DsVUuUrYLEESQoR3Pch5sOID8XuHeWLg5A", host: "taiga.server.net", referrer: "https://taiga.server.net/project/test/wiki/home"
taiga-gateway  | 192.168.122.44 - - [13/Apr/2021:06:49:30 +0000] "GET /media/attachments/9/2/d/8/49bb53eaf8b5cb56ed84d9ece67f69bd4686531ebadf200dcb75a87c743d/taiga-gitlab-flow.jpg?token=YHU-9Q%3AV2WrDTqA3kElb9Kw9qRxfTWqdb7HfRDpZFpcaW5sjb1WoYFLJAE7DsVUuUrYLEESQoR3Pch5sOID8XuHeWLg5A HTTP/1.0" 404 153 "https://taiga.server.net/project/test/wiki/home" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "27.32.199.44"
taiga-protected | 172.18.18.142 - - [13/Apr/2021:06:49:30 +0000] "GET //attachments/9/2/d/8/49bb53eaf8b5cb56ed84d9ece67f69bd4686531ebadf200dcb75a87c743d/taiga-gitlab-flow.jpg?token=YHU-9Q%3AV2WrDTqA3kElb9Kw9qRxfTWqdb7HfRDpZFpcaW5sjb1WoYFLJAE7DsVUuUrYLEESQoR3Pch5sOID8XuHeWLg5A HTTP/1.0" 200 0 "https://taiga.server.net/project/test/wiki/home" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"

```

However the file is not found by the gateway.

Perhaps I have `taiga-protected` configured incorrectly.  Should it also have access to the `media` and `static` directories?

**Comment by zeigerpuppy** [comment]
In answer to my comment above... yes, the `media` dir does need to be accessible to `taiga-gateway` and `taiga-protected`.  
They are mounted at `/taiga/media`.

It's possible this error affected me as I need so explicitly specify volumes (using kata-containers).
