### ISSUE TITLE
[BUG] can't sendmail

### ISSUE THREAD

**Issue by jeffery9** [taigaio/taiga-docker#4]
**Describe the bug**

have configured the "django.core.mail.backends.smtp.EmailBackend" 
and run `sendtestemail` 

it report sendmail success, but not received email, and check the email account, found that have not call the smtp server/

```
+ exec docker-compose -f docker-compose.yml -f docker-compose-inits.yml run --rm taiga-manage sendtestemail -v 3 --traceback jeffery@outlook.com
Creating taiga-6_taiga-manage_run ... done
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: Test email from d5ae5d04ac2c on 2021-05-04 12:51:35.201950+00:00
From: system@taiga.io
To: jeffery@outlook.com
Date: Tue, 04 May 2021 12:51:35 -0000
Message-ID: <162013269520.1.6033746653539765163@d5ae5d04ac2c>

If you're reading this, it was successful.


```

**How can we reproduce the behavior**

**Workarounds**

**Screenshots**

**Taiga environment**

 taiga 6.0.2 in docker

**Desktop (please complete the following information):**
 - **OS:** 
 - **Browser:** 
 - **Version:** 

**Additional context**

**Comment by adventurist** [comment]
I seem to be experiencing this

**Comment by daniel-herrero** [comment]
Hi @jeffery9,

I've been able to send a message following the [30min-setup guide](https://resources.taiga.io/30min-setup/) and everything seems to be working properly. It seems more a problem with the SMTP server or with the configuration.

To help you discard this issue, I recommend you to follow the steps I followed to perform the test:

I used [mailtrap](https://mailtrap.io/inboxes) as the SMTP server, with the following settings:
![smtp_settings](https://user-images.githubusercontent.com/4539017/128004286-2bb6b41e-24fc-4293-a9fb-c0a6296c2cdc.png)

Then, write the previous configuration in your `docker-compose.yml`:
```:yaml
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "no-reply@example.com"

  EMAIL_USE_TLS: "False"
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: "smtp.mailtrap.io"
  EMAIL_PORT: 25
  EMAIL_HOST_USER: "553a89627f22e9"
  EMAIL_HOST_PASSWORD: "a69c0c74134105"
```

Start Taiga again (`docker-compose up -d`) and try to receive in the SMTP server the email sent by Taiga to reset the password (enter a valid user's email here), by accessing this URL:
http://local.taiga.io:9000/forgot-password
![forgot_passwd](https://user-images.githubusercontent.com/4539017/128005624-821874a5-48fe-432b-96f1-c18fdc6bfe2f.png)

You should be receiving the email:
![recover_password_email](https://user-images.githubusercontent.com/4539017/128003923-6a1b0898-f1a1-4253-a576-c5535c1c9a72.png)

Please, follow these steps and left us know if it works.
