### ISSUE TITLE
[Q] How to set default language

### ISSUE THREAD

**Issue by gusarg81** [taigaio/taiga-docker#43]
Hi, is there a way to set the default language for Taiga in this docker? Example, I want to set the default language to Spanish (without the need to set in every user creation).

I only see this variable in conf.json. So, I ask if this is the right place.

Thanks.

**Comment by Xaviju** [comment]
Yes, you should update the variable in `conf.json`.
Follow the instructions here: https://resources.taiga.io/30min-setup/#map-a-confjson-file
