### ISSUE TITLE
Unable to make docker image to work

### ISSUE THREAD

**Issue by yalios** [taigaio/taiga-docker#43]
I cant seem to be able to make the docker image work on a non localhost setup.

I am using the docker images from the docker hub below:
https://registry.hub.docker.com/r/taigaio/taiga-back/
https://registry.hub.docker.com/r/taigaio/taiga-front/

**taiga-back**
On taiga-back i used:
TAIGA_SITES_DOMAIN=192.168.1.2:9000
TAIGA_SITES_SCHEME=http
CSRF_COOKIE_SECURE=False
SESSION_COOKIE_SECURE=False

The database connection is working; I can see the tables being created with no issues.
When accessing http://192.168.1.2:8000/api/v1/ I get a list of the APIs, so that seems to be working as well.

**taiga-front**
on taiga-front I used
TAIGA_URL=http://192.168.1.2:9000

When opening http://192.168.1.2:9000 I am redirected to http://192.168.1.2:9000/discover which is expected, however it gives me the message "Something happened and the Taiga has captured the error to be able to work on it."

When looking at the DevTools (F12) i see the below errors:
app-loader.js:1 Your conf.json file is not a valid json file, please review it.
elements.js:1 GET http://localhost:8000/api/v1/stats/discover net::ERR_CONNECTION_REFUSED
elements.js:1 GET http://localhost:8000/api/v1/projects?discover_mode=true&order_by=-total_fans_last_week net::ERR_CONNECTION_REFUSED
elements.js:1 GET http://localhost:8000/api/v1/projects?discover_mode=true&order_by=-total_activity_last_week net::ERR_CONNECTION_REFUSED
elements.js:1 GET http://localhost:8000/api/v1/projects?discover_mode=true&is_featured=true net::ERR_CONNECTION_REFUSED

Why is it still pointing to localhost? Shouldn't be http://192.168.1.2:8000?

Thanks

**Comment by yamila-moreno** [comment]
Hi @yalios the error says that your "conf.json" is not valid. It seems that some configurations made a bad json so the web is not working.

You can:
`docker exec -ti taiga-docker_taiga-front_1 /bin/sh`

and inside the container

`cat /usr/share/nginx/html/conf.json`

and take a look. Maybe you need quotes for the URL or other configuration is wrong. Can you paste the content of the `conf.json` ?

thanks!

**Comment by BCsabaEngine** [comment]
You can edit docker-compose.yml before ./launch-taiga. Url and schema should be 192.168.1.2 instead of localhost.

**Comment by yalios** [comment]
> Hi @yalios the error says that your "conf.json" is not valid. It seems that some configurations made a bad json so the web is not working.
> 
> You can:
> `docker exec -ti taiga-docker_taiga-front_1 /bin/sh`
> 
> and inside the container
> 
> `cat /usr/share/nginx/html/conf.json`
> 
> and take a look. Maybe you need quotes for the URL or other configuration is wrong. Can you paste the content of the `conf.json` ?
> 
> thanks!

Hi @yamila-moreno  I checked the conf.json and i wasn't able spot any issues. The port 9000 seems like it should be 8000, but when i specify the environmental variable of TAIGA_URL=http://192.168.1.2:9000 that is what is automatically updated in the conf-json. below is a copy of the contents

thanks!

{
    "api": "http://172.16.10.2:9000/api/v1/",
    "eventsUrl": "/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": false,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "defaultLoginEnabled": true,
    "publicRegisterEnabled": False,
    "feedbackEnabled": true,
    "supportUrl": "https://resources.taiga.io",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "gitHubClientId": "",
    "gitLabClientId": "",
    "gitLabUrl": "",
    "tagManager": { "accountId": null },
    "tribeHost": null,
    "enableAsanaImporter": false,
    "enableGithubImporter": ,
    "enableJiraImporter": ,
    "enableTrelloImporter": ,
    "gravatar": false,
    "rtlLanguages": ["fa"]
}

**Comment by yalios** [comment]
> You can edit docker-compose.yml before ./launch-taiga. Url and schema should be 192.168.1.2 instead of localhost.

I trying not to go down that path cause my knowledge with docker is a bit limited but i assigned the environmental variables based on the readme instructions which i am assume will result to the same outcome. thanks,

**Comment by AceMX** [comment]
> 
> 
> > You can edit docker-compose.yml before ./launch-taiga. Url and schema should be 192.168.1.2 instead of localhost.
> 
> I trying not to go down that path cause my knowledge with docker is a bit limited but i assigned the environmental variables based on the readme instructions which i am assume will result to the same outcome. thanks,

Can you post your .yml file ? You need to change all the localhost to 192.168.1.2 in there.

I'm having some troubles here too, Taiga starts without problems, but when I try to send any kind of mail, I get some error. I'll post it here later on.

**Comment by yamila-moreno** [comment]
Hi @yalios these configurations in your `conf.json` are creating the problem:

```
"enableGithubImporter": ,
"enableJiraImporter": ,
"enableTrelloImporter": ,
```

this is not a valid json.

Please, pull the latest taiga-front image and taiga-docker and pase the front configuration if you may.

Cheers!

**Comment by yalios** [comment]
> Hi @yalios these configurations in your `conf.json` are creating the problem:
> 
> ```
> "enableGithubImporter": ,
> "enableJiraImporter": ,
> "enableTrelloImporter": ,
> ```
> 
> this is not a valid json.
> 
> Please, pull the latest taiga-front image and taiga-docker and pase the front configuration if you may.
> 
> Cheers!

Thanks @yamila-moreno ! That fixed it. 
Great to see an official supported docker taigaio!

**Comment by yalios** [comment]
> > > You can edit docker-compose.yml before ./launch-taiga. Url and schema should be 192.168.1.2 instead of localhost.
> > 
> > 
> > I trying not to go down that path cause my knowledge with docker is a bit limited but i assigned the environmental variables based on the readme instructions which i am assume will result to the same outcome. thanks,
> 
> Can you post your .yml file ? You need to change all the localhost to 192.168.1.2 in there.
> 
> I'm having some troubles here too, Taiga starts without problems, but when I try to send any kind of mail, I get some error. I'll post it here later on.

I am using the docker images from the hub
