### ISSUE TITLE
Manage dbshell - psql missing

### ISSUE THREAD

**Issue by BCsabaEngine** [taigaio/taiga-docker#44]
**Describe the bug**
I am happy to use taiga-manage.sh to manage system. The dbshell command cannot run, because "CommandError: You appear not to have the 'psql' program installed or on your path."

**To Reproduce**
1. Go to taiga-manage.sh
2. Run ./taiga-manage.sh dbshell

**Expected behavior**
Open postgres console

**Versions**
 - docker 20.10.3
 - docker-compose 1.18.0

**Comment by yamila-moreno** [comment]
we prefer to keep the image as small as possible so we don't plan to add more dependencies if we can avoid it; you can achieve this same access in different ways in your host:

```
docker exec -ti taiga-docker_taiga-db_1 psql -U DB_USER DB_NAME
```
or
```
docker-compose exec taiga-db psql -U DB_USER DB_NAME
```

**Comment by BCsabaEngine** [comment]
Perfect solution, thank you.
