### ISSUE TITLE
[Q] How to set up an admin for taiga?

### ISSUE THREAD

**Issue by TheBlapse** [taigaio/taiga-docker#50]
I have deployed taiga but neither created an admin user nor the default admin user with username `admin` and password `123123` is working, could anyone help me creating one.

**Comment by yamila-moreno** [comment]
Hi @TheBlapse, in the [official documentation](https://resources.taiga.io/30min-setup/) you can find the following:

![imagen](https://user-images.githubusercontent.com/3340793/141944615-3e4e9e79-8001-4df6-b79a-0c87288ccbe8.png)

With this command, you can create an admin for your taiga instance. Cheers!

**Comment by TheBlapse** [comment]
Hey yes I did that, but now the sign up is not working, could you help me with it? it shows the option to signing up but when you click on the sign up button after filling up the details nothing happens.
