### ISSUE TITLE
[Q] how can i change the domain name?

### ISSUE THREAD

**Issue by andrewchenshx** [taigaio/taiga-docker#54]
i've read the "1.1. How can I change the domain name?" on the FAQ page.
it seems it's for the source installation. while for the docker installation, what conf should be updated?

thanks

**Comment by yamila-moreno** [comment]
Hi @andrewchenshx check the official documentation here: https://resources.taiga.io/30min-setup/
You'll find all the information about what to configure. 
Good luck!
