### ISSUE TITLE
taiga don't show imagens with proxy reverse

### ISSUE THREAD

**Issue by felipeolvr** [taigaio/taiga-docker#54]
![image](https://user-images.githubusercontent.com/19410029/109425054-c9b7a380-79bc-11eb-878c-bd1603d1fd20.png)

**Comment by terafirmanz** [comment]
further than I get. if I goto the container address e.g. http://10.1.1.1:8081 (I edited the compose file to use this port) I get the app fine.

When I go to the URL set in compose (points to HAProxy that is doing ssl offloading) e.g. https://taiga.example.com I just get a blank page. If I look in the dev sources panel I can see the spinner and css that creates teh image you show above.

Is there somethign we should be doing for reverse proxy ssl offload?

**Comment by terafirmanz** [comment]
> further than I get. if I goto the container address e.g. http://10.1.1.1:8081 (I edited the compose file to use this port) I get the app fine.
> 
> When I go to the URL set in compose (points to HAProxy that is doing ssl offloading) e.g. https://taiga.example.com I just get a blank page. If I look in the dev sources panel I can see the spinner and css that creates teh image you show above.
> 
> Is there somethign we should be doing for reverse proxy ssl offload?

Solved my issue with this:

`TAIGA_WEBSOCKETS_URL: "ws://talia.example.org"`
changed to:
`TAIGA_WEBSOCKETS_URL: "wss://talia.example.org"`
I was not sending websockets over a secure connection when the site was using https. Maybe a note in the documentation to advise users to change ws to wss when connecting over secure.

**Comment by yamila-moreno** [comment]
Hi @terafirmanz cool you figured it out!

Which documentation did you use? We can improve it for sure!

**Comment by terafirmanz** [comment]
> Hi @terafirmanz cool you figured it out!
> 
> Which documentation did you use? We can improve it for sure!

Hi, I was thinking just a comment in the docker-compose.yml file but I was using both the 30 minutes to and the Github readme files to figure out what env variables do. A note anywhere in these places would help people not miss that point when switching to secure connections (as we all should).

**Comment by yamila-moreno** [comment]
We'll definitely check it. Thanks!

Closing this issue because the original topic is solved.
