### ISSUE TITLE
Generic OAuth2 login options for SSO

### ISSUE THREAD

**Issue by terafirmanz** [taigaio/taiga-docker#55]
**Is your feature request related to a problem? Please describe.**
No generic SSO option, this assumes that you are using Gitlab or Github and offers login via them but I can't use my own SSO service

**Describe the solution you'd like**
Add a generic OAuth2 option even better would be OAuth2 and SAML options

**Describe alternatives you've considered**
Pointing it at Gitlab that is then pointed at my SSO but that is not ideal and only works for users with Gitlab

**Comment by yamila-moreno** [comment]
Hi @terafirmanz currently we offer the authentication options that we support. There are other authentication systems available and we plan to improve the way they are integrated, and even make some of them official as well.

Meanwhile, you can choose a contrib that fits your needs and extend the official image. You can check the official Dockerfiles to have more context.

Cheers!
