### ISSUE TITLE
Events - HTTP 426 Upgrade Required

### ISSUE THREAD

**Issue by BlackQube** [taigaio/taiga-docker#57]
After putting Taiga on my server, I'm getting a Websocket failure. When I look into the dev-tools and get the 
"GET wss://<MY-DOMAIN>/events  HTTP/1.1 426 Upgrade Required <some time in ms>"

Do you have any advice for me? What for aditional Informations do you need for a failure like this?

**Comment by yamila-moreno** [comment]
Hi @BlackQube we'd need to check:
- [ ] docker-compose configuration **with credentials redacted**
- [ ] nginx configuration
- [ ] is there anything properly running if you check `docker-compose ps` ?
- [ ] paste any relevant logs

**Comment by BlackQube** [comment]
> 
> 
> Hi @BlackQube we'd need to check:
> 
>     * [ ]  docker-compose configuration **with credentials redacted**
files are attached here: [docker-taiga.zip](https://github.com/taigaio/taiga-docker/files/6075184/docker-taiga.zip)


>     * [ ]  nginx configuration
my domain simply points to the publicated port to the taiga-gateway container

 
>     * [ ]  is there anything properly running if you check `docker-compose ps` ?
docker-compose ps looks fine


>     * [ ]  paste any relevant logs
where do I get these logs from?

**Comment by BlackQube** [comment]
Well, I guess, I got it working.

Plesk is running on the Host system. So I simply used the Docker Proxy settings from Plesk. Everything worked, except the /event Websocket connection.

Now I disabled the Plesk docker proxy and set up the manual Additional nginx directives identical like in taiga.conf for / and /events, but with "*proxy_pass http://localhost:<publicport>*"

Well, I think the "insecure" http connections are internally only, what is fine, I guess.

Do you have any additional suggestions about that?

**Comment by yamila-moreno** [comment]
Hi @BlackQube glad you figured it out.

Your final nginx seems fine, as it's consistent to [the official one](https://resources.taiga.io/30min-setup/#configure-the-proxy).

Closing this issue, cheers!
