### ISSUE TITLE
[Q] Docker installation and taiga did not run at all

### ISSUE THREAD

**Issue by ranrinc** [taigaio/taiga-docker#57]
&gt; **READ THIS FIRST!**: We recently announced Taiga plans for the future and they greatly affect how we manage this repository and the current Taiga 6 release. Check it [here](https://blog.taiga.io/announcing_taiganext.html).chore: readme announce taiga-next

I run docker installation to the dot and so far upon completion taiga did run but I can see nothing accept this screen

![Screen Shot 2021-12-17 at 9 15 38 AM](https://user-images.githubusercontent.com/15801696/146478131-224e9662-130a-4699-8754-584499f61c63.png)

This error message shown during my first running `./taiga-manage.sh createsuperuser`

```
You have 51 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): projects, references, sessions, settings, tasks, telemetry, timeline, token_denylist, users, userstorage, userstories, votes, webhooks, wiki.
Run 'python manage.py migrate' to apply them.
```

my step-by-step:

***Pre Installation:***
OS: Debian Bullseye
Docker:  20.10.12
Docker Compose: 1.29.2
NGINX Reverse Proxy installed

* git clone this repo
* cd taiga-docker
* git checkout stable
* edit docker-compose.yml and docker-compose-inits.yml
* run ./launch-all.sh
* run ./taiga-manage.sh createsuperuser

More help is needed. Thanks

**Comment by Maxklos** [comment]
I have exactly the same problem. You closed the issue so I think that you got it working. How did you get it running?

**Comment by ranrinc** [comment]
try to check https://github.com/kaleidos-ventures/taiga-docker/issues/46
