### ISSUE TITLE
[Q] How to connect taiga to AWS SES for sending email and how to make public register to true

### ISSUE THREAD

**Issue by ranrinc** [taigaio/taiga-docker#59]
&gt; **READ THIS FIRST!**: We recently announced Taiga plans for the future and they greatly affect how we manage this repository and the current Taiga 6 release. Check it [here](https://blog.taiga.io/announcing_taiganext.html).chore: readme announce taiga-next

1. Need help since the server never sending email through SES even though its was set correctly
2. Adding `PUBLIC_REGISTER_ENABLED: "True"` under X-environment: + on taiga-front doesn't to be working at all. If I commented it out Taiga will work. But when its not commented out I got a blank pages.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
