### ISSUE TITLE
can not set external postgres port in docker-compose.yml POSTGRES_PORT: 3333

### ISSUE THREAD

**Issue by krswin** [taigaio/taiga-docker#60]
**Describe the bug**
When trying to set a custom postgres port in docker-compose.yml it takes default(5432) postgres port. 
POSTGRES_PORT: 3333 # do not work **OR** POSTGRES_HOST: 192.168.2.10:3333 # do not work

**To Reproduce**
1. set in docker-compose file : POSTGRES_HOST: 192.168.2.10:3333
2. OR try to set port in docker-compose file : POSTGRES_PORT: 3333

**Expected behavior**
in docker-compose.yml file I want to set a POSTGRES PORT for external postgres database instance running on other port like 3333

Thank you for help.

**Comment by yamila-moreno** [comment]
Hi @krswin thanks for reporting.

Meanwhile, you could use your own config.py mapped, as explained here: https://resources.taiga.io/30min-setup/#advanced-configuration

**Comment by yamila-moreno** [comment]
Hi @krswin we've pushed a new docker image that exposes POSTGRES_PORT and it's documented here: https://taigaio.github.io/taiga-doc/dist/setup-production.html#_configuration

cheers!

**Comment by krswin** [comment]
Thank you for quick solution. Now it works great. Have a good day.
