### ISSUE TITLE
[Q] 500 Internal Server Error and 502 Bad Gateway

### ISSUE THREAD

**Issue by dekm** [taigaio/taiga-docker#60]
We recently had to update a setting in our local taiga instance for email.

After stopping the docker containers, updating the docker-compose.yml, and restarting all projects are gone. 

We cannot login or see any projects. I was able to backup and dump the db and can see everything is there.

On initial load, the discover page has 500 Internal server errors
![Screenshot from 2022-01-06 12-16-14](https://user-images.githubusercontent.com/9221328/148367544-0f79add3-395d-43e5-83bd-2f9fce767f79.png)

When attempting a login we receive the same. Sometimes the error is also a 502 bad gateway although it seems random.

The server itself is running apache with a subdomain forwarded with https. We also use shorewall as the firewall service.

**Comment by dekm** [comment]
Ended up realizing we had this issue before... Appears there is a permission setting inside the taiga-back on resolv.conf that needs to be set for some reason.

`docker exec -ti taiga-pm_taiga-back_1 /bin/bash`
`chmod o+r /etc/resolv.conf`

was all that needed to be done to resolve this.

**Comment by wolfcreative** [comment]
The error is still present, even with a fresh install.
@dekm solution only works if you type:

`docker exec -ti taiga-docker_taiga-back_1 /bin/bash`
`chmod o+r /etc/resolv.conf`
`exit`
and then
`./launch-all.sh`

**UPD:** There is a chance that you will have to wait. No idea how it works, very strange.
