### ISSUE TITLE
docker-compose.yml taiga-front environment for custom domain do not work

### ISSUE THREAD

**Issue by krswin** [taigaio/taiga-docker#61]
**Describe the bug**
Setting up custom domain using docker-compose.yml do not work.
docker-compose.yml taiga-front environment for custom domain do not work.

  taiga-front:
    image: taigaio/taiga-front:latest
    container_name: taiga-front
    environment:
      TAIGA_URL: http://taiga.custom.com
      TAIGA_WEBSOCKETS_URL: ws://taiga.custom.com
      PUBLIC_REGISTER_ENABLED: "False"
    networks:
      - taiga
    #volumes:
    #   - ./config/conf.json:/usr/share/nginx/html/conf.json

**To Reproduce**
  TAIGA_SITES_DOMAIN: taiga.custom.com
  TAIGA_SITES_SCHEME: http

**Expected behavior**
using docker-compose.yml custom domain should work.

**Configuration**
If applicable, describe the custom configuration that may affect.
Using external nginx proxy(for domain) with taiga-gateway port forward 9000
taiga.custom.com > points to server running IP(taiga-gateway):9000

**Versions**
 - docker: 20+
 - docker-compose 1.27+

**As here you can see upstream is wrong: 192.168.0.1 is internal docker IP address and not the IP address I have defined in my external nginx server.** 

Thank you for help.

**Comment by krswin** [comment]
Just that It only works when I use conf.json file to set this 2 values TAIGA_URL and TAIGA_WEBSOCKETS_URL. but same values are not considered when set via docker-compose and disable the volume file conf.json

**Comment by yamila-moreno** [comment]
Hi @krswin I cannot reproduce this behaviour.
You can use the mounted `conf.json` which is fine, but it you'd like to keep it easy with the environment variables, I'd need that you fill the variables, disable the volume with the conf.json and:
- [ ] describe the error, what does it mean "dont work", is the container up and running? is there an error in the console?
- [ ] once this is up, could you check the `conf.json` inside the docker and confirm if it's a valid one? (you can paste the 5 first lines here)

Cheers!

**Comment by krswin** [comment]
@yamila-moreno Thanks for reply. do not work means containers are correctly started but when opening the URL in web browser white page is shown without any content. 
And When i see network calls from browser this goes to localhost domain which is wrong this means configuration for frontend set in docker-compose.yml is not considered.

This is solved when i use now conf.json. So I do not have this exact error now. But Just for your reference I created this ticket so it can be fixed and help other people. For me everything works fine by setting correct URL in conf.json. 

Thanks.
