### ISSUE TITLE
Named volume for rabbitmq

### ISSUE THREAD

**Issue by burtsevyg** [taigaio/taiga-docker#62]
When I run current docker-compose config I see list of volumes which contains something like this:
local     8ba95867244bea9c94cb4dcc362992d0ffb608f410ad13763cfacbc068cbe408
local     b054b7999db696f1643abcdd68c50e0a375d4f028c6b11358b9545c74c8ed196

After every down/up creates new one.

This volumes ship from rabbitmq images.
May be will be better create named volumes?

Please see:
https://stackoverflow.com/questions/41330514/docker-rabbitmq-persistency

**Comment by yamila-moreno** [comment]
Hi @burtsevyg thanks for reporting.

The named volumes are already available in `master` branch, and will be in `stable` in next release (expected next week).

Cheers!
