### ISSUE TITLE
[Q] CHANGE_NOTIFICATIONS_MIN_INTERVAL in docker-compose.yml

### ISSUE THREAD

**Issue by ponceto** [taigaio/taiga-docker#65]
Hi,

I would like to change the interval for sending email (the famous variable `CHANGE_NOTIFICATIONS_MIN_INTERVAL`)

I'm not sure if there is a way to do this in the docker-compose.yml and I've not found such informations in the documentation.

Thanks for your response.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
