### ISSUE TITLE
Email invite in stdout

### ISSUE THREAD

**Issue by Sepl9100** [taigaio/taiga-docker#68]
Hello,
i want to use taiga for my small school project with two friends.
i succesfully installed the docker container.
However, if i try to send them a email with my SMTP server, that does not work.
The documentation says:  "By default, email is configured with the console backend, which means that the emails will be shown in the stdout."
Where can i look them up?
Thanks in advance!

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
