### ISSUE TITLE
How to use SMTP on Taiga docker

### ISSUE THREAD

**Issue by mjakubowskilkr** [taigaio/taiga-docker#70]
How to use SMTP on Taiga docker?
I've started Taiga from docker, but don't know how to send emails.
All needed parameters are set but when I'm trying to set anything, it's doing nothing. I've tried to show logs of taiga-back container but it doesn't show any smtp activity. Could you explain me how to set it properly?

**Comment by Xaviju** [comment]
Hi there! 

Do you know that we created [Taiga Community](https://community.taiga.io/c/technical/8) for questions like yours? Please, check there; maybe another user has already asked something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.
