### ISSUE TITLE
[Q] Custom port causes 502 for /admin

### ISSUE THREAD

**Issue by milopeach** [taigaio/taiga-docker#75]
When I'm trying to connect to the /admin page I get a 502 from the gateway. I'm running a custom port for the gateway - even though I wanted to run it through my own nginx proxy it seems the configuration is highly against that.

I've tried changing ports for the gateway, changing ports for front, and back, and exposing back directly to connect but that also doesn't work.

If I access the database directly I can see 'users_user' which were made through 'python manage.py createsuperuser'. I would assume from reading that I can only use these to login to /admin, but I've also read the /admin is just a CRUD wrapper for the db itself.

I've also tried multiple 'python manage.py runserver ip:port' configurations.

Why am I getting a 502 for /admin?
Why can't I log in with users created through manage.py?
Which table in the db handles basic user authentication through /login?

**Comment by daniel-herrero** [comment]
Hi @milopeach,

First I would discard you're accessing the Django admin panel from the correct URL, that is `/admin/` and not `/admin` (pay attention to the final back slash).

I would then discard a connection problem between front-end, back-end and the database, reviewing your browser's console while navigating and reloading some pages searching for any error. Taiga should admit any port configuration as long as it is consistent between the different Taiga's services (including Django admin).

Can you please send us your configuration files (`docker-compose.yml`/ `docker-compose-inits.yml`) and your starting logs (`$ docker-compose logs`)? Do you have access to Taiga's API (back) navigating to `<TAIGA_UTL>/api/v1/`?

You should for sure be able to log in with users created through the manage.py command (like `manage.py createsuperuser`). If you have access to the database, I would suggest you to create a user and verify a new register is created in the table `users_user` with its hahsed password in the `password` column. Then you should be able to use this user to both log in both the Taiga and the `\admin\` panel.

Thanks in advance

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
