### ISSUE TITLE
[Q] How can I add a theme that will be selectable in profile settings?

### ISSUE THREAD

**Issue by tikacp** [taigaio/taiga-docker#76]
I've been trying to add a theme to Taiga but I cannot get it to work.
I'm trying to rebuild a taiga-front docker container that holds this theme, but even if the files seem to be there
`/usr/share/nginx/html/v-1643209941013/styles/theme-taiga.css` and `/usr/share/nginx/html/v-1643209941013/styles/theme-taiga-dark.css`
and the conf.json has
`"themes": ["taiga", "taiga-dark"],`
the theme does not show up in the drop-down menu for theme selection.

What else am I missing?

**Comment by tikacp** [comment]
a full `gulp deploy` of taiga-front keeps failing with

> [17:04:32] 'copy-images' errored after 14 s
> [17:04:32] Error in plugin "gulp-imagemin"
> Message:
>     write EPIPE
> Details:
>     errno: EPIPE
>     code: EPIPE
>     syscall: write
>     stdout: 
>     stderr: 
>     failed: true
>     signal: null
>     cmd: /opt/taiga-docker/taiga-front/node_modules/mozjpeg/vendor/cjpeg
>     timedOut: false
>     killed: false
>     fileName: /opt/taiga-docker/taiga-front/app/images/invitation_bg.jpg
>     domainEmitter: [object Object]
>     domainThrown: false

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
