### ISSUE TITLE
How we can personlize email template

### ISSUE THREAD

**Issue by Aicha-cher** [taigaio/taiga-docker#77]
**Is your feature request related to a problem? Please describe.**
can we change the email template ?

**Describe the solution you'd like**
change the email template from within taiga

**Comment by Xaviju** [comment]
Hi there! 
We have created [Taiga Community](https://community.taiga.io/c/give-feedback/7) site for suggestions like yours. Please, check there; maybe another user has already asked something similar. If not, you can create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify the process, we will systematically close all issues and redirect people to Taiga Community.
