### ISSUE TITLE
How can I access app/themes?

### ISSUE THREAD

**Issue by dieguit** [taigaio/taiga-docker#78]
Hello!
In taiga docs it mentions we can use themes and override some styling. I deployed using docker-compose, but I cannot find the app/themes folder in the taiga-front container.
Any ideas?

Thanks!
D.

**Comment by bluefalcon26** [comment]
The docker arch is designed for deployment of packages as slimmed-down as possible. Thus custom themes can't reasonably be supported in the docker deployment code, imo.

The best way is to download the taiga-front code, do whatever theming you need to there, and the build your own docker image of taiga-front. Then, modify the docker-compose.yml:
```
taiga-front:  
    # image: taigaio/taiga-front:latest
    image: YourSpecialRepo/taiga-front:specialTheme
      ...
```
Finally, rebuild and deploy.
