### ISSUE TITLE
[Q] What is the default user in the docker installation?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [taigaio/taiga-docker#83]
I tried admin / 123123 , it's not that.

**Comment by schwederski** [comment]
After installation you have to create a user. You can choose a username and password. Follow the steps in the read-me file. you create the user with "./taiga-manage.sh createsuperuser".

**Comment by yoelvd** [comment]
From the location where you held docker-compose.yml just run this: **_docker-compose -f docker-compose.yml -f docker-compose-inits.yml run --rm taiga-manage createsuperuser_**

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
