### ISSUE TITLE
[Q] Import taiga project gives 403 Forbidden

### ISSUE THREAD

**Issue by diego-cqen** [taigaio/taiga-docker#84]
Hi,

I have Taiga installed in AWS (EKS). Everything else is working fine, but the import function gives me a 403 not authorized response.

Request URL: https://mytaigaadress.com/api/v1/importer/load_dump
Request Method: POST
Status Code: 403 

The import is from Taiga to Taiga and I didn't find anything in the logs to help me understand.

These are the request headers:

accept: application/json
accept-encoding: gzip, deflate, br
accept-language: fr-CA,fr;q=0.9,en-US;q=0.8,en;q=0.7
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU0MDkxMTYzLCJqdGkiOiIxNmYyYjAwZjNiMjg0N2FjOTcxNjYxYjc0ZTU4ODc0OSIsInVzZXJfaWQiOjY0fQ.G17PiO2AVq7yEhioGoY_Y3a2D6H_z7fyzPaXwSsiZ2g
content-length: 112843
content-type: multipart/form-data; boundary=----WebKitFormBoundaryg4D9Pxaclb6GVEIH
cookie: csrftoken=anAWp6JjfnGxrZljzhdKHKUR9v6vCh2a36IHpbFYwaAfTJTujkt9ViXym80biJfZ; AWSALB=rco75wCt9ZnGcxMAXPTviI7fpmnr4k8lQegVLDMoXUVWlPxU+wPsshSHzPGhQ4hx/yROFASkKcMtAuTedZwVuwfSben0UjhXU6sPueepFDsY4P/cZbaMo6NFsNSE; AWSALBCORS=rco75wCt9ZnGcxMAXPTviI7fpmnr4k8lQegVLDMoXUVWlPxU+wPsshSHzPGhQ4hx/yROFASkKcMtAuTedZwVuwfSben0UjhXU6sPueepFDsY4P/cZbaMo6NFsNSE
origin: https://mytaigaadress.com
referer: https://mytaigaadress.com/project/new/import
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin

So, I'm not sure if it is a bug or not. For all others features, it is working pretty fine.

Thank you so much.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
