### ISSUE TITLE
[FR] Add documentation for minor version updates with copy and pastable code snippets

### ISSUE THREAD

**Issue by nuokh** [taigaio/taiga-docker#9]
**Please describe the problem / need you are trying to solve.**
  As a docker noob I have trouble finding out how to do a minor update, for example 6.0 to 6.1.

**Describe the feature or the improvement you'd like and what are you trying to achieve.**
  I would love to see an addition to the wiki that explains the docker container update process with copy & pastable code snippets.

**Describe alternatives you've considered**
  I looked through the docs but only found documentation regarding big upgrades, for example Taiga 5 to Taiga 6.

**Comment by yamila-moreno** [comment]
Hi @nuokh ! Could you take a look at https://github.com/kaleidos-ventures/taiga-doc/pull/3 and tell us if it's understandable?
thanks!

**Comment by nuokh** [comment]
Looks great, thanks for the quick response!
