### ISSUE TITLE
[BUG] Penpot environment variables are not read

### ISSUE THREAD

**Issue by panchtatvam** [taigaio/taiga-docker#95]
**Description**
This is regarding Penpot integrated with Taiga. Penpot can't read some environment variables from `docker-compose.penpot.env` file.

**How can we reproduce the behavior**
Running `./launch-all.sh` creates both Taiga and Penpot. Penpot is however not able to read all Penpot configuration values like to disable registration.

**Workarounds**
The docker and env files of Penpot should be updated to Penpot official [docker](https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml) and [environment](https://raw.githubusercontent.com/penpot/penpot/main/docker/images/config.env) files as mentioned in [Penpot docs](https://help.penpot.app/technical-guide/getting-started/#start-penpot).

There are two major issues not allowing Penpot configuration to be not read :

1. Not using PENPOT_FLAGS in `docker-compose.penpot.env` file
As per latest [Penpot upgrade](https://github.com/penpot/penpot/blob/develop/CHANGES.md#boom-breaking-changes--deprecations-1), `PENPOT_REGISTRATION_ENABLED`  is finally removed in favour of `<enable|disable>-registration` flag. Such environment flags should thus be used via `PENPOT_FLAGS` setting. eg. `PENPOT_FLAGS="enable-registration enable-login"`

2. Settings file for `penpot-exporter` in `docker-compose.penpot.yml`
`env` variables are not set for `penpot-exporter` setting. This needs to set to the env setting as set for all other services ie.

```
env_file:
    - docker-compose.penpot.env
```

3. using PENPOT_TENANT=pro in `docker-compose.penpot.env` file
I am not sure what this setting does, but it seems to impact this issue. You are requested to confirm this setting with the Penpot team. I have already [asked](https://community.penpot.app/t/what-is-the-use-of-penpot-tenant/620) them the use of this setting though.

**Screenshots**
Not applicable

**Taiga environment**
Self hosted Taiga on Fedora 36 Linux with Penpot.

**Desktop (please complete the following information):**
 - **OS:** Fedora 36 Linux
 - **Browser:** Firefox
 - **Version:** 6.0.4

**Additional context**
Got this information about Penpot flags via [troubleshooting help](https://community.penpot.app/t/unable-to-disable-user-registration-in-self-hosted-penpot/614/2) from the Penpot community.

**Comment by niwinz** [comment]
I think all the issues should be solved. We have merged a few PR's updating the compose and the env files.

Thanks!
