### ISSUE TITLE
I want to know what caused this error. The Docker image runs normally without any error

### ISSUE THREAD

**Issue by cow11023** [taigaio/taiga-docker#98]
![image](https://user-images.githubusercontent.com/29158284/195491977-0df9a63f-4630-470d-9a10-cced25f3b836.png)

**Comment by cow11023** [comment]
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/29158284/195493708-28ed95a9-7410-4238-89a2-ce2cce8c1612.png">

**Comment by Helicorp** [comment]
Same problem here

**Comment by bardic** [comment]
Had the same issue. This comment solved it for me 

https://github.com/kaleidos-ventures/taiga-docker/issues/90#issuecomment-1264472550

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
