### ISSUE TITLE
[Q] Editor does not load

### ISSUE THREAD

**Issue by TobiBurger** [taigaio/taiga-docker#99]
We do have a self-hosted instance of taiga. The editor for commenting, e.g. in user stories, does not load. Also, when trying to edit a description or a wiki entry, the WYSIWYG-editor won't show up. Has this happened to anyone else oder does anyone have any hints what might cause this?
Thanks a lot!
![Bildschirmfoto 2022-10-13 um 13 48 06](https://user-images.githubusercontent.com/29768732/195818571-60fbdcee-3a6e-4306-8059-3292dda0acaf.jpeg)
![Bildschirmfoto 2022-10-13 um 13 47 32](https://user-images.githubusercontent.com/29768732/195818576-19fb205e-f27e-4dbb-9e3d-08eac11cde91.jpeg)

**Comment by Xaviju** [comment]
Closing because is duplicated
